name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Git 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 프로젝트에 사용하는 Node.js 버전

      # 3. 종속성 설치
      - name: Install dependencies
        run: npm install

      # 4. 애플리케이션 빌드 (필요한 경우)
      - name: Build application
        run: npm run build

      # 5. Cypress 테스트 실행
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm start # 개발 서버 시작 명령어
          wait-on: "http://localhost:3001" # 서버가 올라올 때까지 대기
          browser: chrome # 실행할 브라우저
